### ISSUE TITLE
Continued project reorg

### ISSUE THREAD

**Issue by davidrpugh** [EconomicSL/housing-model#43]
@adrian-carro Now that the project follows Maven conventions we can start thinking about how to reorganize the packages within the model itself.  Do we envision this model eventually becoming a housing module within ESL? If so, then we should use the reverse domain name convention and put everything inside a `org.economicsl.housing` package.

Within that `housing` package I think we need to have the following sub-packages 
```
financial
household
government
```
Organizing principle would be to organize the sub-packages around economic "sectors."  Does seem reasonable? What sectors am I missing?

**Comment by adrian-carro** [comment]
@davidrpugh I'm not necessarily opposed to this reorganisation... but I really don't think this is relevant at this point: the housing model is currently a separate project, completely independent from the ESL...

**Comment by davidrpugh** [comment]
@adrian-carro OK.  So no need to worry about obeying the reverse domain-name standard for root package naming conventions.  Fine.

How much code cleanup and refactoring of the housing code do you need to do?  The code base is a mess (one that I know you inherited) and I am willing to help you clean it up and refactor it as desired as it helps improve my Java skills.

**Comment by adrian-carro** [comment]
Closing this issue as more than a year without activity and a reorganisation is not a priority at this point. Some of these ideas are likely to be picked up in the context of an upcoming new project with the Bank in the next few months, but will depend on the specific new modules to be implemented, which are still to be decided upon. In any case, that new project might migrate to a separate repository, so no need to keep this issue here.
